#!/bin/sh
#
# --- Command line
refname="$1"
oldrev="$2"
newrev="$3"

# --- Safety check
if [ -z "$GIT_DIR" ]; then
	echo "Don't run this script from the command line." >&2
	echo " (if you want, you could supply GIT_DIR then run" >&2
	echo "  $0 <ref> <oldrev> <newrev>)" >&2
	exit 1
fi

if [ -z "$refname" -o -z "$oldrev" -o -z "$newrev" ]; then
	echo "usage: $0 <ref> <oldrev> <newrev>" >&2
	exit 1
fi

missed_rev="git rev-list $oldrev..$newrev"
error_msg="Aborting commit. Your commit message is missing an issue identifier"
commit_regex="(^Merge branch.+)|(^[A-Z]{3}-[0-9]{3}::)"

# TODO: take into account merge commits

$missed_rev | while read commit; do
    if !  git cat-file $commit | sed '1,/^$/d' | grep -i $commit_regex; then
        echo "$error_msg" >&2
        exit 1
    fi
done 

# --- Finished
exit 0
